### ISSUE TITLE
Make a REST service for TextService to count characters and words

### ISSUE THREAD

**Issue by haraldfianbakken** [haraldfianbakken/qsec-7#1]
Provide basic service with the following features

Character Count - Counts the characters in a provided string
Word Count - Counts the number of words in a string

Generic requirements

Service should designed according to RESTful principles
Easy to get up an running on developer machine and in the cloud
Service should able to handle multiple requests at the same time

**Comment by karl-henrik** [comment]
I will work on this unless someone else have claimed it.

**Comment by theplastictoy** [comment]
@karl-henrik still working on it?

**Comment by karl-henrik** [comment]
yes
